// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//user,sku,category,query,click_time,query_time
type Signal struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId                string   `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	CatId                string   `protobuf:"bytes,3,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	ClickTime            int64    `protobuf:"varint,5,opt,name=click_time,json=clickTime,proto3" json:"click_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (m *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(m, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

func (m *Signal) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Signal) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func (m *Signal) GetCatId() string {
	if m != nil {
		return m.CatId
	}
	return ""
}

func (m *Signal) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Signal) GetClickTime() int64 {
	if m != nil {
		return m.ClickTime
	}
	return 0
}

type QueryDocSignalHourly struct {
	DocId                string   `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	EpochHour            int32    `protobuf:"varint,3,opt,name=epoch_hour,json=epochHour,proto3" json:"epoch_hour,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDocSignalHourly) Reset()         { *m = QueryDocSignalHourly{} }
func (m *QueryDocSignalHourly) String() string { return proto.CompactTextString(m) }
func (*QueryDocSignalHourly) ProtoMessage()    {}
func (*QueryDocSignalHourly) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *QueryDocSignalHourly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDocSignalHourly.Unmarshal(m, b)
}
func (m *QueryDocSignalHourly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDocSignalHourly.Marshal(b, m, deterministic)
}
func (m *QueryDocSignalHourly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDocSignalHourly.Merge(m, src)
}
func (m *QueryDocSignalHourly) XXX_Size() int {
	return xxx_messageInfo_QueryDocSignalHourly.Size(m)
}
func (m *QueryDocSignalHourly) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDocSignalHourly.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDocSignalHourly proto.InternalMessageInfo

func (m *QueryDocSignalHourly) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func (m *QueryDocSignalHourly) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryDocSignalHourly) GetEpochHour() int32 {
	if m != nil {
		return m.EpochHour
	}
	return 0
}

func (m *QueryDocSignalHourly) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryCatSignalHourly struct {
	CatId                string   `protobuf:"bytes,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	EpochHour            int32    `protobuf:"varint,3,opt,name=epoch_hour,json=epochHour,proto3" json:"epoch_hour,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCatSignalHourly) Reset()         { *m = QueryCatSignalHourly{} }
func (m *QueryCatSignalHourly) String() string { return proto.CompactTextString(m) }
func (*QueryCatSignalHourly) ProtoMessage()    {}
func (*QueryCatSignalHourly) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *QueryCatSignalHourly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCatSignalHourly.Unmarshal(m, b)
}
func (m *QueryCatSignalHourly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCatSignalHourly.Marshal(b, m, deterministic)
}
func (m *QueryCatSignalHourly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCatSignalHourly.Merge(m, src)
}
func (m *QueryCatSignalHourly) XXX_Size() int {
	return xxx_messageInfo_QueryCatSignalHourly.Size(m)
}
func (m *QueryCatSignalHourly) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCatSignalHourly.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCatSignalHourly proto.InternalMessageInfo

func (m *QueryCatSignalHourly) GetCatId() string {
	if m != nil {
		return m.CatId
	}
	return ""
}

func (m *QueryCatSignalHourly) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryCatSignalHourly) GetEpochHour() int32 {
	if m != nil {
		return m.EpochHour
	}
	return 0
}

func (m *QueryCatSignalHourly) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Signal)(nil), "model.Signal")
	proto.RegisterType((*QueryDocSignalHourly)(nil), "model.QueryDocSignalHourly")
	proto.RegisterType((*QueryCatSignalHourly)(nil), "model.QueryCatSignalHourly")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x31, 0x4f, 0x43, 0x21,
	0x14, 0x85, 0x43, 0x2b, 0x98, 0x77, 0xdd, 0x48, 0x8d, 0x6f, 0x31, 0x69, 0x3a, 0x75, 0x72, 0xf1,
	0x27, 0xe8, 0x60, 0x47, 0xd1, 0xfd, 0x05, 0x2f, 0xc4, 0x12, 0x79, 0xbd, 0x15, 0x21, 0xb1, 0xbb,
	0x3f, 0xdc, 0x70, 0x31, 0x4d, 0xf3, 0xe2, 0xd6, 0xf1, 0x7c, 0x01, 0xbe, 0x73, 0x02, 0x5c, 0x8d,
	0xe4, 0x7c, 0xbc, 0xdb, 0x27, 0xca, 0xa4, 0x25, 0x87, 0xd5, 0x8f, 0x00, 0xf5, 0x12, 0xde, 0x77,
	0x36, 0xea, 0x1b, 0xb8, 0x2c, 0x5f, 0x3e, 0x0d, 0xc1, 0xf5, 0x62, 0x29, 0xd6, 0x9d, 0x51, 0x35,
	0x6e, 0x9c, 0xbe, 0x06, 0xe5, 0x08, 0x2b, 0x9f, 0x31, 0x97, 0x8e, 0xb0, 0x61, 0xb4, 0xb9, 0xe2,
	0x79, 0xc3, 0x68, 0xf3, 0xc6, 0xe9, 0x05, 0xc8, 0xcf, 0xe2, 0xd3, 0xa1, 0xbf, 0x68, 0x94, 0x83,
	0xbe, 0x05, 0xc0, 0x18, 0xf0, 0x63, 0xc8, 0x61, 0xf4, 0xbd, 0x5c, 0x8a, 0xf5, 0xdc, 0x74, 0x4c,
	0x5e, 0xc3, 0xe8, 0x57, 0xdf, 0xb0, 0x78, 0xae, 0xe7, 0x1e, 0x09, 0x5b, 0x9b, 0x27, 0x2a, 0x29,
	0x1e, 0x4e, 0xd4, 0xe2, 0x54, 0x7d, 0x74, 0xcc, 0x26, 0x0e, 0xbf, 0x27, 0xdc, 0x0e, 0x5b, 0x2a,
	0x89, 0x4b, 0x49, 0xd3, 0x31, 0xa9, 0xaf, 0xd5, 0x4b, 0x48, 0x65, 0x97, 0xb9, 0x98, 0x34, 0x2d,
	0x1c, 0xcd, 0x0f, 0x36, 0x4f, 0xcd, 0x7f, 0xeb, 0xc4, 0xbf, 0xeb, 0xce, 0x36, 0xbf, 0x29, 0xfe,
	0x88, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x5b, 0xa9, 0x7a, 0x97, 0x01, 0x00, 0x00,
}
